import { promises as fs } from 'node:fs';
import path from 'node:path';
import fse from 'fs-extra';
import { storageCall } from './storage-store.js';
import { assertInsideBase, readDataAsBase64, statSafe } from './file-store.js';
import { decryptString, encryptString } from './safe-storage.js';
import { config } from './config.js';
async function fsCall(action: string, payload: any): Promise<unknown> { switch (action) { case 'copy': await fse.copy(assertInsideBase(payload.path), assertInsideBase(payload.dest), { overwrite:true }); return true; case 'output-json': await fse.outputJson(assertInsideBase(payload.path), payload.data, { spaces:2 }); return true; case 'read-json': return fse.readJson(assertInsideBase(payload)); case 'ensureDir': await fse.ensureDir(assertInsideBase(payload)); return true; case 'pathExists': return fse.pathExists(assertInsideBase(payload)); case 'remove': await fse.remove(assertInsideBase(payload)); return true; case 'writeFile': { const p = assertInsideBase(payload.path); await fse.ensureDir(path.dirname(p)); await fs.writeFile(p, typeof payload.data === 'string' ? payload.data : String(payload.data ?? ''), payload.mode ? { mode:payload.mode } : undefined); return true; } case 'mkdir': await fs.mkdir(assertInsideBase(payload.path), { recursive:true, mode:payload.mode }); return true; case 'readFile': return fs.readFile(assertInsideBase(payload), 'utf8'); case 'readdir': return fs.readdir(assertInsideBase(payload)); case 'stat': return statSafe(payload); case 'unlink': await fs.unlink(assertInsideBase(payload)); return true; case 'readData': return readDataAsBase64(payload); case 'isFile': try { return (await fs.stat(assertInsideBase(payload))).isFile(); } catch { return false; } default: throw new Error(`Unsupported fs action: ${action}`); } }
export async function dispatchIpc(channel: string, payload: any): Promise<unknown> { if (channel.startsWith('storage:')) return storageCall(channel.slice(8), payload); if (channel.startsWith('fs:')) return fsCall(channel.slice(3), payload); switch (channel) { case 'safeStorage:isEncryptionAvailable': return true; case 'safeStorage:encryptString': return encryptString(payload); case 'safeStorage:decryptString': return decryptString(payload); case 'safeStorage:getSelectedStorageBackend': return 'server'; case 'dialog:open': return { canceled:true, filePaths:[] }; case 'dialog:save': return { canceled:true, filePath:null }; case 'dialog:message': return { response:0 }; case 'app:info': return { name:'Beaver Notes Web', version:'4.4.0-web', platform:process.platform }; case 'app:notification': case 'app:spellcheck': case 'app:set-zoom': case 'app:change-menu-visibility': case 'theme:set': case 'renderer-ready': return { success:true }; case 'app:get-zoom': return 1; case 'helper:get-path': return config.data.dir; case 'helper:is-dark-theme': return false; case 'get-system-fonts': return ['Arial','Helvetica','Times New Roman','Courier New','Verdana','sans-serif','serif','monospace']; case 'print-pdf': return { success:false, disabled:true, reason:'Use browser print' }; case 'check-for-updates': case 'download-update': case 'install-update': case 'helper:relaunch': case 'open-file-external': case 'download-file': return { success:false, disabled:true }; case 'toggle-auto-update': return { success:true, enabled:false }; case 'get-auto-update-status': case 'is-update-downloading': return false; case 'get-update-info': return { currentVersion:'4.4.0-web', availableVersion:null, isChecking:false, isDownloading:false }; default: return { success:true, ignored:channel }; } }
